/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        "primary-dynata-brighter": "var(--primary-dynata-brighter)",
        "primary-dynata-bright": "var(--primary-dynata-bright)",
        "primary-dynata-lighter": "var(--primary-dynata-lighter)",
        "primary-dynata-light": "var(--primary-dynata-light)",
        "primary-dynata-normal": "var(--primary-dynata-normal)",
        "primary-dynata-dark": "var(--primary-dynata-dark)",

        "primary-blue-brighter": "var(--primary-blue-brighter)",
        "primary-blue-bright": "var(--primary-blue-bright)",
        "primary-blue-light": "var(--primary-blue-light)",
        "primary-blue-normal": "var(--primary-blue-normal)",
        "primary-blue-dark": "var(--primary-blue-dark)",
        "primary-blue-deep": "var(--primary-blue-deep)",

        "secondary-blue-brighter": "var(--secondary-blue-brighter)",
        "secondary-blue-bright": "var(--secondary-blue-bright)",
        "secondary-blue-light": "var(--secondary-blue-light)",
        "secondary-blue-normal": "var(--secondary-blue-normal)",
        "secondary-blue-dark": "var(--secondary-blue-dark)",
        "secondary-blue-deep": "var(--secondary-blue-deep)",

        "secondary-magenta-brighter": "var(--secondary-magenta-brighter)",
        "secondary-magenta-bright": "var(--secondary-magenta-bright)",
        "secondary-magenta-light": "var(--secondary-magenta-light)",
        "secondary-magenta-normal": "var(--secondary-magenta-normal)",
        "secondary-magenta-dark": "var(--secondary-magenta-dark)",
        "secondary-magenta-deep": "var(--secondary-magenta-deep)",

        "secondary-orange-brighter": "var(--secondary-orange-brighter)",
        "secondary-orange-bright": "var(--secondary-orange-bright)",
        "secondary-orange-light": "var(--secondary-orange-light)",
        "secondary-orange-normal": "var(--secondary-orange-normal)",
        "secondary-orange-dark": "var(--secondary-orange-dark)",
        "secondary-orange-deep": "var(--secondary-orange-deep)",

        "danger-brighter": "var(--danger-brighter)",
        "danger-bright": "var(--danger-bright)",
        "danger-light": "var(--danger-light)",
        "danger-normal": "var(--danger-normal)",
        "danger-dark": "var(--danger-dark)",
        "danger-deep": "var(--danger-deep)",

        "warning-brighter": "var(--warning-brighter)",
        "warning-bright": "var(--warning-bright)",
        "warning-light": "var(--warning-light)",
        "warning-normal": "var(--warning-normal)",
        "warning-dark": "var(--warning-dark)",
        "warning-deep": "var(--warning-deep)",

        "info-brighter": "var(--info-brighter)",
        "info-bright": "var(--info-bright)",
        "info-light": "var(--info-light)",
        "info-normal": "var(--info-normal)",
        "info-dark": "var(--info-dark)",
        "info-deep": "var(--info-deep)",

        "positive-brighter": "var(--positive-brighter)",
        "positive-bright": "var(--positive-bright)",
        "positive-light": "var(--positive-light)",
        "positive-normal": "var(--positive-normal)",
        "positive-dark": "var(--positive-dark)",
        "positive-deep": "var(--positive-deep)",

        "gray-1": "var(--gray-1)",
        "gray-2": "var(--gray-2)",
        "gray-3": "var(--gray-3)",
        "gray-4": "var(--gray-4)",
        "gray-5": "var(--gray-5)",
        "gray-6": "var(--gray-6)",
        "gray-7": "var(--gray-7)",
        "gray-8": "var(--gray-8)",
        "gray-9": "var(--gray-9)",
        "gray-10": "var(--gray-10)",
        "gray-11": "var(--gray-11)",
        "gray-12": "var(--gray-12)",
        "gray-13": "var(--gray-13)",
      },
    },
  },
};
